import React from 'react'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faCity, faMoneyCheckDollar, faPenToSquare, faUser} from '@fortawesome/free-solid-svg-icons';
function Impact() {
  return (
    <div className='p-8 flex justify-center flex-col items-center'>
        <div className='text-xl md:text-2xl font-bold text-center'>Impact</div>  
        <div className='flex w-full md:w-4/5 justify-center flex-wrap'>
            <div className='flex  justify-center w-1/2 md:w-1/4'>
            <div className='flex flex-col text-[#0693e3] text-center gap-3 text-2xl md:text-6xl p-3'> 
                <FontAwesomeIcon className='border p-6 rounded-full rounded-tl-none shadow-2xl' icon={faCity}/>
                <div className='text-sm md:text-xl'>
                    220+ <br/>
                    STARTUPS
                </div>
            </div>
            </div>  
            <div className='flex justify-center w-1/2 md:w-1/4'>
                <div className='flex flex-col items-center text-[#0693e3] text-center gap-3 text-2xl md:text-6xl p-3'> 
                    <FontAwesomeIcon className='border p-6 rounded-full rounded-tl-none shadow-2xl' icon={faPenToSquare}/>
                    <div className='text-sm md:text-xl'>
                        1000+<br/>
                        ENTREPRENEURS 
                    </div>
                </div>
            </div>  
            <div className='flex justify-center w-1/2 md:w-1/4'>
                <div className='flex flex-col items-center text-[#0693e3] text-center gap-3 text-2xl md:text-6xl p-3'> 
                    <FontAwesomeIcon className='border p-6  rounded-full rounded-tl-none shadow-2xl' icon={faUser}/>
                    <div className='text-sm md:text-xl'>
                        6300+<br/>
                        EMPLOYMENT Generated by RJIT
                    </div>
                </div>
            </div>  
            <div className='flex justify-center w-1/2 md:w-1/4'>
                <div className='flex flex-col items-center text-[#0693e3] text-center gap-3 text-2xl md:text-6xl p-3'> 
                    <FontAwesomeIcon className='border p-6 rounded-full rounded-tl-none shadow-2xl' icon={faMoneyCheckDollar}/>
                    <div className='text-sm md:text-xl'>
                        INR 6224 Cr.<br/>
                        FUNDS RAISED by RJIT Startups
                    </div>
                </div>
            </div>  
        </div>
    </div>
  )
}

export default Impact